name: Intégration en continu

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  # ==========================
  # FRONTEND (Vue dans /public)
  # ==========================
  frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: public
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node (frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: public/package-lock.json

      - run: npm ci
      - run: npm run build
      - run: npm test --if-present

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-dist
          path: public/dist
          if-no-files-found: ignore

  # ==========================
  # BACKEND (Express dans /api)
  # ==========================
  backend:
    name: Test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node (backend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: api/package-lock.json

      - run: npm ci
      - run: npm test --if-present
      - run: npm run build --if-present
